providers = ["node"]

[variables]
VITE_SUPABASE_URL = "https://xpmbnznsmsujjuwumfiw.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbWJuem5zbXN1amp1d3VtZml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0NTcxODAsImV4cCI6MjA4NDAzMzE4MH0.90vGineFlNuSJ10hMD_lWHnc6DCUgWQZubfR-X_0tO4"
VITE_GOOGLE_CLIENT_ID = "your-google-client-id"
VITE_BILLIONMAIL_API_URL = "https://mail.bravita.com.tr/api/v1"
VITE_FIREBASE_API_KEY = "AIzaSyA2Du9w8wZhz3F6IFfoQnHNT81MsD0OUG0"
VITE_FIREBASE_AUTH_DOMAIN = "abiding-pod-369018.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "abiding-pod-369018"
VITE_FIREBASE_STORAGE_BUCKET = "abiding-pod-369018.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "594702594542"
VITE_FIREBASE_APP_ID = "1:594702594542:web:82a8aa9ea16049ed7c9eff"
VITE_FIREBASE_MEASUREMENT_ID = "G-PX3J2YF2KV"
VITE_FIREBASE_PHONE_TEST_MODE = "true"
VITE_RECAPTCHA_SITE_KEY = "6LdJ0kotAAAAAA0_yOy1Gsy2EaxT4RSqHwxOPWK7"
VITE_RECAPTCHA_SECRET_KEY = "6LdJ0kotAAAAAKGorj7pCHN2DkyUb4a4bO_S-HWS"
